<a href="https://colab.research.google.com/github/gtzambranop/UN_2020_2/blob/DCD%2Fweek_4/DCD/module_2/basic_python_class_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **"Pyhton Básico"**

* **Profesor:** Francisco Javier Ospina Salazar
* **Monitoras:**
  - Diana Carolina Sanchez Perez
  - Guiselle Tatiana Zambrano Penagos
* **Fechas:** 
  - Inicio: 2020-09-12
  - Final: 2020-09-29
* [Presentacióón del curso](http://ospinafrancisco.com/)


## Contenido de la clase

- Objetos
  - Clases
    - Métodos
    - Atributos
  - Módulos para manipulación de datos en python
    - Numpy
    - Pandas



# Clases u Objetos

Los objetos son abstracciones de elementos reales o no reales que disponen de atributos y funciones que permiten interactuar con esos atributos.

## Métodos mágicos - **Dunders**

Son métodos especiales que tienen **doble guión bajo** al principio y al final de sus nombres.

Un uso común de estos es la **sobrecarga de operadores**. Esto significa definir operadores para clases personalizadas que permiten que operadores tales como `+`, `and`, `*` sean utilizados en ellas

Ejemplo de `__add__` para `+`:

In [124]:
class Vector2D:
  # TODOS los métodos de una clase deben tener 'self' como su primer parámetro
  def __init__(self, x, y):
    self.x = x;
    self.y = y
  
  def __add__(self, other):
    # Retorno una nueva instancia de la clase Vector2D donde:
    # x = la suma del atributo x de los 2 vectores
    # y = la suma del atributo y de los 2 vectores
    return Vector2D((self.x + other.x), (self.y + other.y))

In [125]:
first = Vector2D(8, 9)
second = Vector2D(2, 3)

# first + second -> utilizan el método __add__ que sobrecarga el operador +
# Es decir, se redefine el operador +

# Esto se traduce a: 
#result = first.__add__(second) # DESCOMENTAR LINEA - se ejecuta con normalidad
result = first + second

# La suma retorna una instancia que es asignada a la variable 'result'
print(type(result))


<class '__main__.Vector2D'>


In [126]:
print(result.x) # 8 + 2 = 10 = first.x + second.x
print(result.y) # 9 + 3 = 12 = first.y + second.y

10
12


### Más métodos mágicos para operadores comunes

- `__sub__` para `-`
- `__mul__` para `*`
- `__truediv__` para `/`
- `__floordiv__` para `//`
- `__mod__` para `%`
- `__pow__` para `**`
- `__and__` para `&`
- `__xor__` para `^`
- `__or__` para `|`
- `__lt__` para `<`
- `__le__` para `<=`
- `__eq__` para `==`
- `__ne__` para `!=`
- `__gt__` para `>`
- `__ge__` para `>=`

Hay más métodos mágicos pero no los voy a poner todos [acá](https://www.reddit.com/r/Python/comments/br9ok2/list_of_all_python_dunder_methods/) encontré un foro donde enlistan muchos más


In [127]:
# Otro ejemplo

class SpecialString:
  def __init__(self, cont):
    self.cont = cont

  # sobrecarga del operador '/'
  def __truediv__(self, other):
    # Multiplicamos el string "=" por la longitud del string other.cont
    line = "=" * len(other.cont)
    return "\n".join([self.cont, line, other.cont])

In [128]:
spam = SpecialString("Spam Spam :p")
hello = SpecialString("Hello World :D")

result = spam.__truediv__(hello)
print(result)

Spam Spam :p
Hello World :D


In [129]:
print(spam/hello)

Spam Spam :p
Hello World :D


### Cómo construir clases
* Debe haber una definición de la clase
* Debe haber un método **init** cuya función es la de inicializar los atributos de la clase
* Para referirse a los elementos (atributos o funciones) de la clase utilizamos el la entencia "self."
* Nota: Es importante tener claridad sobre la "notación punto"

#### Ejemplo con clase tiempo
* Version 0: Clase nula
* Version 1: Clase simple
* Version 2: Validando horas correctas
* Version 3: Dando formato para poder visualizar con la función str
* Version 4: Clase completa vista en clase

##### Version 0: Clase *nula*

In [130]:
# Version 0 Clase nula
class Tiempo():
    pass

In [131]:
t1 = Tiempo()

##### Version 1: Clase simple

In [132]:
class Tiempo():
  def __init__(self, hora = 0, minuto = 0, segundo = 0):
    # Definicion e inicialización de atributos de un objeto de la clase tiempo
    self.hora = hora
    self.minuto = minuto
    self.segundo = segundo


t1 = Tiempo(19, 22, 35)
print(t1.hora, t1.minuto, t1.segundo)

19 22 35


##### Version 2: Validando horas correctas

In [133]:
class Tiempo():
  def __init__(self, hora=0, minuto=0, segundo=0):
        self.hora = 0 if hora < 0 or hora > 23 else hora
        self.minuto = 0 if minuto < 0 or minuto > 59 else minuto
        self.segundo = 0 if segundo < 0 or segundo > 59 else segundo
        

t1 = Tiempo(-19, 22, 399)
print("{}:{}:{}".format(t1.hora, t1.minuto, t1.segundo))


0:22:0


In [134]:
t1 = Tiempo(19, 32, 39)
print("{}:{}:{}".format(t1.hora, t1.minuto, t1.segundo))

19:32:39


##### Version 3: Dando formato para poder visualizar con la función str


In [135]:
class Tiempo():
  def __init__(self, hora=0, minuto=0, segundo=0):
        self.hora = 0 if hora < 0 or hora > 23 else hora
        self.minuto = 0 if minuto < 0 or minuto > 59 else minuto
        self.segundo = 0 if segundo < 0 or segundo > 59 else segundo
        
  # Método invocado al hacer uso de la función print de python          
  def __str__(self):
      hora_str = str(self.hora) if self.hora > 9 else '0' + str(self.hora)
      minuto_str = str(self.minuto) if self.minuto > 9 else '0' + str(self.minuto)
      segundo_str = str(self.segundo) if self.segundo > 9 else '0' + str(self.segundo)
      return '{}:{}:{}'.format(hora_str, minuto_str, segundo_str)

In [136]:
t1 = Tiempo(19, 32, 39)
print(t1)


19:32:39


#### Versióón 4: Clase completa vista en clase

In [137]:

class tiempo(): # Nombre de la clase
    
    def __init__(self, hora=0, minuto=0, segundo=0):
        # Definición de paramétros internos de la clase
        
        self.hora = 0 if hora < 0 or hora > 23 else hora
        self.minuto = 0 if minuto < 0 or minuto > 59 else minuto
        self.segundo = 0 if segundo < 0 or segundo > 59 else segundo
        
    # Metodo que recibe los parametros hora, minuto y segundo y los suma a mi clase tiempo actual
    def suma_hms(self, hora=0, minuto=0, segundo=0):
        self.segundo = self.segundo + segundo
        if self.segundo > 59: # Si segundo supera 60 se transforman 60 segundos a minuto
            self.segundo = self.segundo % 60
            self.minuto = self.minuto + 1
        self.minuto = self.minuto + minuto
        if self.minuto > 59: # Si segundo supera 60 se transforman 60 segundos a minuto
            self.minuto = self.minuto % 60
            self.hora = self.hora + 1
        self.hora = self.hora + hora # Si hora supera 24 quiere decir que ya pasó un día y se pasó al siguiente
        if self.hora > 23:
            self.hora = self.hora % 24
            
    # A pesar de no haber sido definido el atributo franja al inicio de la clase se puede crear posteriormente
    def set_franja_horaria(self):
        if self.hora < 12: 
            self.franja = 'mañana'
        elif self.hora >= 12 and self.hora < 19:
            self.franja = 'tarde'
        else:
            self.franja = 'noche'
    
    # Un método de una clase puede invocar a otros métodos
    def suma_tiempo(self, t2):
        self.suma_hms(hora=t2.hora, minuto=t2.minuto, segundo=t2.segundo)
        self.set_franja_horaria()
        
    # Uso de el operador + para hacer una suma de tiempos
    # Esto tiene un nombre en programación y es sobrecarga del operador +
    def __add__(self, t2):
        temp = tiempo(hora=self.hora, minuto=self.minuto, segundo=self.segundo)
        temp.suma_tiempo(t2)
        return temp
    
    # Método invocado al hacer uso de la función print de python          
    def __str__(self):
        hora_str = str(self.hora) if self.hora > 9 else '0' + str(self.hora)
        minuto_str = str(self.minuto) if self.minuto > 9 else '0' + str(self.minuto)
        segundo_str = str(self.segundo) if self.segundo > 9 else '0' + str(self.segundo)
        return '{}:{}:{}'.format(hora_str, minuto_str, segundo_str)

## Herencia en Clases


La Herencia brinda una manera de compartir funcionalidades entre clases.

Una clase que hereda de otra clase se le llama **Subclase**.

Una clase de la cual se hereda se llama **Superclase**.

In [138]:
class punto_2d():
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    # Sobrescritura para el método print de python
    def __str__(self):
        return '({},{})'.format(self.x, self.y)

In [139]:
punto1 = punto_2d(2,5)
print(punto1)

(2,5)


In [140]:
class punto_3d():    
    def __init__(self, x, y, z):
        self.p2d = punto_2d(x,y)
        self.z = z
    
    def __str__(self):
        return '({},{},{})'.format(self.p2d.x, self.p2d.y, self.z)

In [141]:
punto2 = punto_3d(2,5,8)
print(punto2)

(2,5,8)


### Otro ejemplo de Herencia de clases

In [142]:
class Animal:
  def __init__(self, name, color):
    self.name = name
    self.color = color

# Indico que la clase Cat hereda de la clase Animal
# Por lo tanto la clase Cat hereda los atributos name y color
class Cat(Animal):
  def purr(self):
    print("Purr :3")

# Indico que la clase Dog hereda de la clase Animal
# Por lo tanto la clase Cat hereda los atributos name y color
class Dog(Animal):
  def bark(self):
    print("Woof! :p")

In [143]:
# Al instanciar un objeto de la clase Dog, ingreso los atributos
# name y color que fueron heredados de la clase Animal
fido = Dog("Fido", "Brown")

# Accedo a un atributo de un objeto usando
# nombre_objeto.nombre_atributo
print(fido.color)

# Accedo a un método de un objeto usando
# nombre_objeto.nombre_metodo() -> NO olvidar los parentesis al final
fido.bark()

Brown
Woof! :p


In [144]:
# Al instanciar un objeto de la clase Cat, ingreso los atributos
# name y color que fueron heredados de la clase Animal
luna = Cat("Luna", "Black and Gray")

# Accedo a un atributo de un objeto usando
# nombre_objeto.nombre_atributo
print(luna.name)

# Accedo a un método de un objeto usando
# nombre_objeto.nombre_metodo() -> NO olvidar los parentesis al final
luna.purr()

Luna
Purr :3


Si una clase hereda de otra con los mismos atributos o métodos, los sobrescribe.

In [145]:
class Wolf:
  def __init__(self, name, color):
    self.name = name
    self.color = color
  
  def bark(self):
    print("Grrr... >:v")

class Dog(Wolf):
  # Acá sobrescribo el método bark que fué heredado de la clase Wolf
  def bark(self):
    # Ya no va a imprimir "Grrr... >:v" sino "Woof :p"
    print("Woof :p")

In [146]:
max = Wolf("Max", "Grey")
max.bark()

Grrr... >:v


In [147]:
jack = Dog("Jack", "Black")
jack.bark()

Woof :p


## Ocultamiento de Información

Un componente clave en la programación orientada a objetos es el **encapsulamiento**, que involucra empaquetar las variables y funciones relacionadas en un único objeto fácil de usar.

Un concepto asociado es el **ocultamiento de información**, el cual dicta que los **detalles** de implementación de una clase deben estar ocultos y que sean presentados a aquellos que quieran utilizar la clase en una interfaz estandar limpia.

En python, no hay maneras de imponer que un método o atributo sea estrictamente privado. 

Se asume que no se forzará el acceso a estos atributos, también se usa esta convensión para evitar errores en caso de qu[texto del enlace](https://)e existan subclases que tengan métodos o atributos con los mismos nombres

### Métodos devilmente tipados

Los métodos y atributos débilmente privados tienen un **único guión bajo** al principio.

Esto señala que son privados, y no deberían ser utilizados por código externo. Sin embargo, es en su mayor parte una convensión, y no impide que el código externo los acceda.

Su único efecto verdadero es que `from module_name import *` no importará a las variables que empiecen con un único guion bajo.

In [148]:
class Person:
  def __init__(self, name, last_name, age, document):
    self.name = name
    self.last_name = last_name
    self.age = age
    # Defino un atributo privado
    self._document = document
    
    # Al atributo full_name se le asigna el resultado 
    # de la función _create_full_name
    # para llamarlo se debe usar la palabra reservada self, así:
    # self._create_full_name
    self.full_name = self._create_full_name()

  # Defino un método privado
  def _create_full_name(self):
    return "{} {}".format(self.name, self.last_name)

In [149]:
tatiana = Person("Tatiana", "Zambrano", "95", "123456789")
# Accedo a un atributo no privado
print(tatiana.full_name)

Tatiana Zambrano


In [150]:
# Aunque estéé marcado como privado, este método puede ser accedido
# por código externo
print(tatiana._create_full_name())

Tatiana Zambrano


In [151]:
print(tatiana._document)

123456789


### Métodos fuertemente tipados

Tienen **doble guion bajo** al principio de sus nombres. Esto hace que sus nombres sean decorados, lo cual significa que no pueden ser accedidos desde afuera de la clase de manera convencional.

Estos métodos o atributos pueden ser accedidos con un nombre diferente:

```python
# inicia con 1 guion bajo
# entre el nombre de la clase y el atributo o método van 2 guiones bajos
_NombreClase__atributo
_NombreClase__metodo
```

In [152]:
class Person:
  def __init__(self, name, last_name, age, document):
    self.name = name
    self.last_name = last_name
    self.age = age
    # Defino un atributo privado
    self.__document = document

    # Al atributo full_name se le asigna el resultado 
    # de la función _create_full_name
    # para llamarlo se debe usar la palabra reservada self, así:
    # self._create_full_name
    self.full_name = self.__create_full_name()

  # Defino un método privado
  def __create_full_name(self):
    return "{} {}".format(self.name, self.last_name)

In [153]:
diana = Person("Diana", "Sanchez", "20", "987654321")
print(diana.full_name)

Diana Sanchez


In [154]:
#print(diana.__create_full_name) # ERROR

In [155]:
# diana._NombreClase__Atributo
print(diana._Person__document)

987654321


In [156]:
# NO olviden los parentesis después del nombre del método
# diana._NombreClase__Método()
print(diana._Person__create_full_name())

Diana Sanchez


# Módulos Numpy y Pandas

## Numpy

Numpy es el módulo fundamental para la computación científica con Python.

* Matrices multidimensionales
* Herramientas avanzadas para algebra líneal
* Funciones para trabajar con número aleatorios
* Su nucleo de procesamiento por debajo de Python está escrito en Fortran y C++

### Carga de módulo de Numpy

In [157]:
import numpy as np

### Tipos de datos en Numpy

* Data type Description
* bool_ Boolean (True or False) stored as a byte
* int_ Default integer type (same as C long; normally either int64 or - int32)
* intc Identical to C int (normally int32 or int64)
* intp Integer used for indexing (same as C ssize_t; normally either - int32 or int64)
* int8 Byte (-128 to 127)
* int16 Integer (-32768 to 32767)
* int32 Integer (-2147483648 to 2147483647)
* int64 Integer (-9223372036854775808 to 9223372036854775807)
* uint8 Unsigned integer (0 to 255)
* uint16 Unsigned integer (0 to 65535)
* uint32 Unsigned integer (0 to 4294967295)
* uint64 Unsigned integer (0 to 18446744073709551615)
* float_ Shorthand for float64.
* float16 Half precision float: sign bit, 5 bits exponent, 10 bits - - mantissa
* float32 Single precision float: sign bit, 8 bits exponent, 23 bits - mantissa
* float64 Double precision float: sign bit, 11 bits exponent, 52 - - bits mantissa
* complex_ Shorthand for complex128.
* complex64 Complex number, represented by two 32-bit floats
* complex128 Complex number, represented by two 64-bit floats

### Creación de Arrays en Numpy

In [158]:
a = np.array([1, 2, 3, 4, 5, 6])   

print(a)
print(type(a))           
print(a.shape) 

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [159]:
a = np.array([0, 1, 2, 3, 4, 5, 6], dtype=np.float64)   

print(a)
print(type(a))
# Imprimir el atributo shape        
print(a.shape)  

[0. 1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
(7,)


#### Creación de arrays especiales
* Arrays con ceros
* Arrays con unos
* Arrays con constante
* Matriz identidad
* Arrays con números aleatorios

##### Arrays con ceros

In [160]:
a = np.zeros((5,3))   

print(a)
print(a.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(5, 3)


In [161]:
a = np.zeros(shape=(4,3,2,1))   

print(a)
print(a.shape)

[[[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]


 [[[0.]
   [0.]]

  [[0.]
   [0.]]

  [[0.]
   [0.]]]]
(4, 3, 2, 1)


##### Arrays con unos

In [162]:
a = np.ones((2,7))    

print(a)  

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


##### Arrays con constante

In [163]:
a = np.full((4,4), 8)  

print(a)     

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


##### Matriz identidad

In [164]:
a = np.eye(5)         

print(a) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##### Arrays con números aleatorios

In [165]:
a = np.random.random((2,3,2))  
print(a) 

[[[0.54013431 0.3546081 ]
  [0.46495058 0.61581664]
  [0.27932342 0.50488062]]

 [[0.72120962 0.62323896]
  [0.77154504 0.80721113]
  [0.36879577 0.8255511 ]]]


#### Indexamiento de arrays de numpy

* Accediendo a elementos por indice
* Accediendo a elementos por slice

##### Accediendo a elementos por indice

In [166]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

#print(a[1])

#print(a[2][3])

#print(a[2,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### Accediendo a elementos por slice

In [167]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a)

# Primeras 2 filas
print(a[:2])

# Ultimas 2 columnas de las 2 primeras filas
print(a[:2,-2:])

# Ultimas 3 columnas de las 2 primeras filas
print(a[:2,-3:])

print(a[::-1, ::-1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]
[[2 3 4]
 [6 7 8]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [168]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1 = a[1]    
row_r2 = a[1:2]  

print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


#### Broadcasting con arrays de Numpy

El broadcasting es coger una operación aritmetica y replicarla a lo largo de un array de numpy

In [169]:
a = np.arange(10)
a = a.reshape((2,5))

b = a + 10

print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


#### Operaciones por columna o por fila

In [170]:
a = np.arange(12)
a = a.reshape((3,4))

print(a)

# 0 + 1 + 2 + ... + 11
print(np.sum(a)) 
print(np.sum(a, axis=0))  
print(np.sum(a, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


#### Operaciones matriciales elemento a elemento

In [171]:
a = np.arange(4)
a = a.reshape(2,2)

b = np.arange(10,14)
b = b.reshape(2,2)

print(a)

print(b)

print(a / b)

[[0 1]
 [2 3]]
[[10 11]
 [12 13]]
[[0.         0.09090909]
 [0.16666667 0.23076923]]


#### Indexado Booleano

In [172]:
a = np.arange(16)
b = np.random.choice(a, 16)
b = b.reshape(4, 4)

matriz_logica = b < 8

c = b.copy()
c[matriz_logica] = -1


print(b,'\n')
print(matriz_logica,'\n')

# Imprimir objetos menores a 8 de la matriz b
print(b[matriz_logica],'\n')

print(b, '\n')

print(c)

[[ 4  8  0 12]
 [10 15  8  5]
 [ 0 10  1  5]
 [ 3  4  1  7]] 

[[ True False  True False]
 [False False False  True]
 [ True False  True  True]
 [ True  True  True  True]] 

[4 0 5 0 1 5 3 4 1 7] 

[[ 4  8  0 12]
 [10 15  8  5]
 [ 0 10  1  5]
 [ 3  4  1  7]] 

[[-1  8 -1 12]
 [10 15  8 -1]
 [-1 10 -1 -1]
 [-1 -1 -1 -1]]


## Pandas
pandas es una biblioteca de código abierto con licencia BSD que proporciona estructuras de datos y herramientas de análisis de datos de alto rendimiento; fáciles de usar para el lenguaje de programación Python.

### Carga de módulo de Pandas

In [173]:
import pandas as pd

### Estructuras de datos en Pandas

* Series
* Dataframes

#### Series

Una serie es un array unidimensional (con tipos de datos de numpy), cada uno de sus elementos está etiquetado. Las etiqueta se llaman índices.

##### Creación de una serie

In [174]:
# Ejemplo

'''
 La primera columna inicia desde 0 por defecto y la segunda columna es poblada
 con los valores especificados en la lista
'''
serie1 = pd.Series([1,2,3,4,5,6])
print(serie1)
print(type(serie1))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>


##### Acceder a elementos e índices de una serie

In [175]:
# Obtener valores
serie1.values

# Obtener índices
serie1.index
list(serie1.index)

[0, 1, 2, 3, 4, 5]

In [176]:
# Ejemplo de serie con index personalizados

serie1 = pd.Series([1,2,3,4,5,6], index=['a', 'b', 'c', 'd', 'e', 'f'])
print(serie1)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64


##### Transformar un diccionario en una serie


In [177]:
# Ejemplo de una Serie construida desde un diccionario

dic = {0: 'a', 1: 'b', 2: 'c'}
pd.Series(dic)

0    a
1    b
2    c
dtype: object

##### Opeaciones con series

* Broadcasting
* indexado booleano

In [178]:
# Ejemplo
import string
print(string.ascii_letters, '\n')
index = list(string.ascii_letters)[:10]

serie1 = pd.Series(np.arange(10), index=index)
print(serie1, '\n')

# Broadcasting
serie2 = serie1 * 3
print(serie2, '\n')

serie3 = np.sqrt(serie1)
print(serie3, '\n')

# Indexado booleano
serie4 = serie1[serie1 >= 5]
print(serie4, '\n')

# Ejemplo con error
# serie5 = serie1[serie1 >= 5 and serie1 <= 7]
'''
El 'and' comun espera dos valores booleanos para operar:
T and F 

Sin embargo se le esta mostrando una lista de valores booleanos: 
[T, F, T, T] and [T, T, F, T] -> error

np.logical_and([T, F, T, T], [T, T, F, T]) = [T, F, F, T]
'''
serie5 = serie1[np.logical_and(serie1 >= 5, serie1 <= 7)]
print(serie5)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ 

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int64 

a     0
b     3
c     6
d     9
e    12
f    15
g    18
h    21
i    24
j    27
dtype: int64 

a    0.000000
b    1.000000
c    1.414214
d    1.732051
e    2.000000
f    2.236068
g    2.449490
h    2.645751
i    2.828427
j    3.000000
dtype: float64 

f    5
g    6
h    7
i    8
j    9
dtype: int64 

f    5
g    6
h    7
dtype: int64


#### Data Frames

Un Dataframe es una estructura de datos que sirve para crear tablas bidimensionales, en donde a cada dimensión tiene etiquetas para acceder a los datos.

##### Creación de dataframes

In [179]:
dc = {'Nombre': ['Francisco', 'Mario', 'Ana', 'Pedro', 'Marta'],
      'Edad': [37, 20, 45, 26, 42],
      'Género': ['M', 'M', 'F', 'M', 'F']}

df1 = pd.DataFrame(dc)
df1


Nombre  Edad Género
0  Francisco    37      M
1      Mario    20      M
2        Ana    45      F
3      Pedro    26      M
4      Marta    42      F

##### Acceso a índices por columnas o por filas

In [180]:
# Ejemplo
# Por columnas
df1.columns

# Por filas
df1.index

RangeIndex(start=0, stop=5, step=1)

##### Acceso a los datos por columnas o por filas

In [181]:
# Ejemplo de acceso por columnas

print(df1['Edad'], '\n') # El retorno es una Serie
print(df1[['Nombre', 'Edad']], '\n')

# Acceder como atributo
print(df1.Edad)

0    37
1    20
2    45
3    26
4    42
Name: Edad, dtype: int64 

      Nombre  Edad
0  Francisco    37
1      Mario    20
2        Ana    45
3      Pedro    26
4      Marta    42 

0    37
1    20
2    45
3    26
4    42
Name: Edad, dtype: int64


In [182]:
# Ejemplo de acceso por filas

# Llaves  Valores de la fila
print(df1.loc[0], '\n') # El retorno es una Serie

print(df1.iloc[0], '\n')

# Diferencias entre loc e iloc
df2 = df1.copy()

# Se redefine el valor de los indices para df2
df2.index = np.arange(10,15)
print(df2, '\n')

#df2.loc[0]
df2.iloc[0]

Nombre    Francisco
Edad             37
Género            M
Name: 0, dtype: object 

Nombre    Francisco
Edad             37
Género            M
Name: 0, dtype: object 

       Nombre  Edad Género
10  Francisco    37      M
11      Mario    20      M
12        Ana    45      F
13      Pedro    26      M
14      Marta    42      F 



Nombre    Francisco
Edad             37
Género            M
Name: 10, dtype: object

In [183]:
# Eliminar personas que sean menores que 40
df2 = df1[df1['Edad'] > 40]
print(df2)

  Nombre  Edad Género
2    Ana    45      F
4  Marta    42      F


In [184]:
df2.iloc[0]

# Hay un error porque el indice 0 fue eliminado, solo estan 2 y 4
#df2.loc[0]

Nombre    Ana
Edad       45
Género      F
Name: 2, dtype: object

##### Obtener todos los elementos de un DataFrame como un array de numpy

In [185]:
# Ejemplob

df1.values

array([['Francisco', 37, 'M'],
       ['Mario', 20, 'M'],
       ['Ana', 45, 'F'],
       ['Pedro', 26, 'M'],
       ['Marta', 42, 'F']], dtype=object)

##### Formas de iterar un dataframe de pandas

* Con un for convencional
* Con un iterrows
* Con una función lambda

In [186]:
! wget https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

--2020-09-19 17:12:07--  https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4551 (4.4K) [application/x-httpd-php]
Saving to: ‘iris.data’

iris.data           100%[===================>]   4.44K  --.-KB/s    in 0s      

2020-09-19 17:12:07 (104 MB/s) - ‘iris.data’ saved [4551/4551]



In [187]:
! head -n 5 iris.data

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa


In [188]:
iris = pd.read_csv('iris.data', header=None)
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']

###### Con un for convencional

In [189]:
from datetime import datetime as dt

start = dt.now()

sepal_box = np.zeros(len(iris))

for index in np.arange(len(iris)):
    row_act = iris.iloc[index]
    sepal_box[index] = row_act['sepal_length'] * row_act['sepal_width']

print(dt.now() - start)

0:00:00.028947


###### Con un iterrows

In [190]:
start = dt.now()

sepal_box = np.zeros(len(iris))

# (index, [...])
for index, row in iris.iterrows():
    sepal_box[index] = row['sepal_length'] * row['sepal_width']
    
print(dt.now() - start)

0:00:00.022447


###### Con una función lambda

In [191]:
def get_box(x):
    return x['sepal_length'] * x['sepal_width']

get_box(iris.iloc[0])

17.849999999999998

In [192]:
start = dt.now()

# axis=1  ->  filas
sepal_box = iris.apply(lambda x: get_box(x), axis=1)

print(dt.now() - start)

0:00:00.012417
