<a href="https://colab.research.google.com/github/gtzambranop/UN_2020_2/blob/DCD%2Fweek_4/DCD/module_2/basic_python_class_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **"Pyhton Básico"**

* **Profesor:** Francisco Javier Ospina Salazar
* **Monitoras:**
  - Diana Carolina Sanchez Perez
  - Guiselle Tatiana Zambrano Penagos
* **Fechas:** 
  - Inicio: 2020-09-12
  - Final: 2020-09-29
* [Presentacióón del curso](http://ospinafrancisco.com/)


## Contenido de la clase

- Objetos
  - Clases
    - Métodos
    - Atributos
  - Módulos para manipulación de datos en python
    - Numpy
    - Pandas



# Clases u Objetos

Los objetos son abstracciones de elementos reales o no reales que disponen de atributos y funciones que permiten interactuar con esos atributos.

### Cómo construir clases
* Debe haber una definición de la clase
* Debe haber un método `__init__` cuya función es la de inicializar los atributos de la clase
* Para referirse a los elementos (atributos o funciones) de la clase utilizamos el la entencia "self."
* Nota: Es importante tener claridad sobre la "notación punto"

## Métodos mágicos - **Dunders**

Son métodos especiales que tienen **doble guión bajo** al principio y al final de sus nombres.

Un uso común de estos es la **sobrecarga de operadores**. Esto significa definir operadores para clases personalizadas que permiten que operadores tales como `+`, `and`, `*` sean utilizados en ellas

Ejemplo de `__add__` para `+`:

In [446]:
class Vector2D:
  # TODOS los métodos de una clase deben tener 'self' como su primer parámetro
  def __init__(self, x, y):
    self.x = x;
    self.y = y
  
  def __add__(self, other):
    # Retorno una nueva instancia de la clase Vector2D donde:
    # x = la suma del atributo x de los 2 vectores
    # y = la suma del atributo y de los 2 vectores
    return Vector2D((self.x + other.x), (self.y + other.y))

In [447]:
first = Vector2D(8, 9)
second = Vector2D(2, 3)

# first + second -> utilizan el método __add__ que sobrecarga el operador +
# Es decir, se redefine el operador +

# Esto se traduce a: 
#result = first.__add__(second) # DESCOMENTAR LINEA - se ejecuta con normalidad
result = first + second

# La suma retorna una instancia que es asignada a la variable 'result'
print(type(result))


<class '__main__.Vector2D'>


In [448]:
print(result.x) # 8 + 2 = 10 = first.x + second.x
print(result.y) # 9 + 3 = 12 = first.y + second.y

10
12


### Más métodos mágicos para operadores comunes

- `__sub__` para `-`
- `__mul__` para `*`
- `__truediv__` para `/`
- `__floordiv__` para `//`
- `__mod__` para `%`
- `__pow__` para `**`
- `__and__` para `&`
- `__xor__` para `^`
- `__or__` para `|`
- `__lt__` para `<`
- `__le__` para `<=`
- `__eq__` para `==`
- `__ne__` para `!=`
- `__gt__` para `>`
- `__ge__` para `>=`

Hay más métodos mágicos pero no los voy a poner todos [acá](https://www.reddit.com/r/Python/comments/br9ok2/list_of_all_python_dunder_methods/) encontré un foro donde enlistan muchos más


In [449]:
# Otro ejemplo

class SpecialString:
  def __init__(self, cont):
    self.cont = cont

  # sobrecarga del operador '/'
  def __truediv__(self, other):
    # Multiplicamos el string "=" por la longitud del string other.cont
    line = "=" * len(other.cont)
    return "\n".join([self.cont, line, other.cont])

In [450]:
spam = SpecialString("Spam Spam :p")
hello = SpecialString("Hello World :D")

result = spam.__truediv__(hello)
print(result)

Spam Spam :p
Hello World :D


In [451]:
print(spam/hello)

Spam Spam :p
Hello World :D


#### Ejemplo con clase tiempo
* Version 0: Clase nula
* Version 1: Clase simple
* Version 2: Validando horas correctas
* Version 3: Dando formato para poder visualizar con la función str
* Version 4: Clase completa vista en clase

##### Version 0: Clase *nula*

In [452]:
# Version 0 Clase nula
class Tiempo():
    pass

In [453]:
t1 = Tiempo()

##### Version 1: Clase simple

In [454]:
class Tiempo():
  def __init__(self, hora = 0, minuto = 0, segundo = 0):
    # Definicion e inicialización de atributos de un objeto de la clase tiempo
    self.hora = hora
    self.minuto = minuto
    self.segundo = segundo


t1 = Tiempo(-19, 22, 35)
print(t1.hora, t1.minuto, t1.segundo)

-19 22 35


##### Version 2: Validando horas correctas

In [455]:
class Tiempo():
  def __init__(self, hora=0, minuto=0, segundo=0):
        self.hora = 0 if hora < 0 or hora > 23 else hora
        self.minuto = 0 if minuto < 0 or minuto > 59 else minuto
        self.segundo = 0 if segundo < 0 or segundo > 59 else segundo
        

t1 = Tiempo(-19, 22, 399)
print("{}:{}:{}".format(t1.hora, t1.minuto, t1.segundo))


0:22:0


In [456]:
t1 = Tiempo(19, 32, 39)
print("{}:{}:{}".format(t1.hora, t1.minuto, t1.segundo))

19:32:39


##### Version 3: Dando formato para poder visualizar con la función str


In [457]:
class Tiempo():
  def __init__(self, hora=0, minuto=0, segundo=0):
        self.hora = 0 if hora < 0 or hora > 23 else hora
        self.minuto = 0 if minuto < 0 or minuto > 59 else minuto
        self.segundo = 0 if segundo < 0 or segundo > 59 else segundo
        
  # Método invocado al hacer uso de la función print de python          
  def __str__(self):
      hora_str = str(self.hora) if self.hora > 9 else '0' + str(self.hora)
      minuto_str = str(self.minuto) if self.minuto > 9 else '0' + str(self.minuto)
      segundo_str = str(self.segundo) if self.segundo > 9 else '0' + str(self.segundo)
      return '{}:{}:{}'.format(hora_str, minuto_str, segundo_str)

In [458]:
t1 = Tiempo(1, 32, 39)
print(str(t1))
print(t1)


01:32:39
01:32:39


#### Versióón 4: Clase completa vista en clase

In [459]:

class tiempo(): # Nombre de la clase
    
    def __init__(self, hora=0, minuto=0, segundo=0):
        # Definición de paramétros internos de la clase
        
        self.hora = 0 if hora < 0 or hora > 23 else hora
        self.minuto = 0 if minuto < 0 or minuto > 59 else minuto
        self.segundo = 0 if segundo < 0 or segundo > 59 else segundo
        
    # Metodo que recibe los parametros hora, minuto y segundo y los suma a mi clase tiempo actual
    def suma_hms(self, hora=0, minuto=0, segundo=0):
        self.segundo = self.segundo + segundo
        if self.segundo > 59: # Si segundo supera 60 se transforman 60 segundos a minuto
            self.segundo = self.segundo % 60
            self.minuto = self.minuto + 1
        self.minuto = self.minuto + minuto
        if self.minuto > 59: # Si segundo supera 60 se transforman 60 segundos a minuto
            self.minuto = self.minuto % 60
            self.hora = self.hora + 1
        self.hora = self.hora + hora # Si hora supera 24 quiere decir que ya pasó un día y se pasó al siguiente
        if self.hora > 23:
            self.hora = self.hora % 24
            
    # A pesar de no haber sido definido el atributo franja al inicio de la clase se puede crear posteriormente
    def set_franja_horaria(self):
        if self.hora < 12: 
            self.franja = 'mañana'
        elif self.hora >= 12 and self.hora < 19:
            self.franja = 'tarde'
        else:
            self.franja = 'noche'
    
    # Un método de una clase puede invocar a otros métodos
    def suma_tiempo(self, t2):
        self.suma_hms(hora=t2.hora, minuto=t2.minuto, segundo=t2.segundo)
        self.set_franja_horaria()
        
    # Uso de el operador + para hacer una suma de tiempos
    # Esto tiene un nombre en programación y es sobrecarga del operador +
    def __add__(self, t2):
        temp = tiempo(hora=self.hora, minuto=self.minuto, segundo=self.segundo)
        temp.suma_tiempo(t2)
        return temp
    
    # Método invocado al hacer uso de la función print de python          
    def __str__(self):
        hora_str = str(self.hora) if self.hora > 9 else '0' + str(self.hora)
        minuto_str = str(self.minuto) if self.minuto > 9 else '0' + str(self.minuto)
        segundo_str = str(self.segundo) if self.segundo > 9 else '0' + str(self.segundo)
        return '{}:{}:{}'.format(hora_str, minuto_str, segundo_str)

## Herencia en Clases


La Herencia brinda una manera de compartir funcionalidades entre clases.

Una clase que hereda de otra clase se le llama **Subclase**.

Una clase de la cual se hereda se llama **Superclase**.

In [460]:
class punto_2d():
    def __init__(self, x, y):
        self.x = x
        self.y = y
    
    # Sobrescritura para el método print de python
    def __str__(self):
        return '({},{})'.format(self.x, self.y)

In [461]:
punto1 = punto_2d(2,5)
print(punto1)

(2,5)


In [462]:
class punto_3d():    
    def __init__(self, x, y, z):
        self.p2d = punto_2d(x,y)
        self.z = z
    
    def __str__(self):
        return '({},{},{})'.format(self.p2d.x, self.p2d.y, self.z)

In [463]:
punto2 = punto_3d(2,5,8)
print(punto2)

(2,5,8)


### Otro ejemplo de Herencia de clases

In [464]:
class Animal:
  def __init__(self, name, color):
    self.name = name
    self.color = color

# Indico que la clase Cat hereda de la clase Animal
# Por lo tanto la clase Cat hereda los atributos name y color
class Cat(Animal):
  def purr(self):
    print("Purr :3")

# Indico que la clase Dog hereda de la clase Animal
# Por lo tanto la clase Cat hereda los atributos name y color
class Dog(Animal):
  def bark(self):
    print("Woof! :p")

In [465]:
# Al instanciar un objeto de la clase Dog, ingreso los atributos
# name y color que fueron heredados de la clase Animal
fido = Dog("Fido", "Brown")

# Accedo a un atributo de un objeto usando
# nombre_objeto.nombre_atributo
print(fido.color)

# Accedo a un método de un objeto usando
# nombre_objeto.nombre_metodo() -> NO olvidar los parentesis al final
fido.bark()

Brown
Woof! :p


In [466]:
# Al instanciar un objeto de la clase Cat, ingreso los atributos
# name y color que fueron heredados de la clase Animal
luna = Cat("Luna", "Black and Gray")

# Accedo a un atributo de un objeto usando
# nombre_objeto.nombre_atributo
print(luna.name)

# Accedo a un método de un objeto usando
# nombre_objeto.nombre_metodo() -> NO olvidar los parentesis al final
luna.purr()

Luna
Purr :3


Si una clase hereda de otra con los mismos atributos o métodos, los sobrescribe.

In [467]:
class Wolf:
  def __init__(self, name, color):
    self.name = name
    self.color = color
  
  def bark(self):
    print("Grrr... >:v")

class Dog(Wolf):
  # Acá sobrescribo el método bark que fué heredado de la clase Wolf
  def bark(self):
    # Ya no va a imprimir "Grrr... >:v" sino "Woof :p"
    print("Woof :p")

In [468]:
max = Wolf("Max", "Grey")
max.bark()

Grrr... >:v


In [469]:
jack = Dog("Jack", "Black")
jack.bark()

Woof :p


## Ocultamiento de Información

Un componente clave en la programación orientada a objetos es el **encapsulamiento**, que involucra empaquetar las variables y funciones relacionadas en un único objeto fácil de usar.

Un concepto asociado es el **ocultamiento de información**, el cual dicta que los **detalles** de implementación de una clase deben estar ocultos y que sean presentados a aquellos que quieran utilizar la clase en una interfaz estandar limpia.

En python, no hay maneras de imponer que un método o atributo sea estrictamente privado. 

Se asume que no se forzará el acceso a estos atributos, también se usa esta convensión para evitar errores en caso de qu[texto del enlace](https://)e existan subclases que tengan métodos o atributos con los mismos nombres

### Métodos devilmente tipados

Los métodos y atributos débilmente privados tienen un **único guión bajo** al principio.

Esto señala que son privados, y no deberían ser utilizados por código externo. Sin embargo, es en su mayor parte una convensión, y no impide que el código externo los acceda.

Su único efecto verdadero es que `from module_name import *` no importará a las variables que empiecen con un único guion bajo.

In [470]:
class Person:
  def __init__(self, name, last_name, age, document):
    self.name = name
    self.last_name = last_name
    self.age = age
    # Defino un atributo privado
    self._document = document
    
    # Al atributo full_name se le asigna el resultado 
    # de la función _create_full_name
    # para llamarlo se debe usar la palabra reservada self, así:
    # self._create_full_name()
    self.full_name = self._create_full_name()

  # Defino un método privado
  def _create_full_name(self):
    return "{} {}".format(self.name, self.last_name)

In [471]:
tatiana = Person("Tatiana", "Zambrano", "95", "123456789")
# Accedo a un atributo no privado
print(tatiana.full_name)

Tatiana Zambrano


In [472]:
# Aunque estéé marcado como privado, este método puede ser accedido
# por código externo
print(tatiana._create_full_name())

Tatiana Zambrano


In [473]:
print(tatiana._document)

123456789


### Métodos fuertemente tipados

Tienen **doble guion bajo** al principio de sus nombres. Esto hace que sus nombres sean decorados, lo cual significa que no pueden ser accedidos desde afuera de la clase de manera convencional.

Estos métodos o atributos pueden ser accedidos con un nombre diferente:

```python
# inicia con 1 guion bajo
# entre el nombre de la clase y el atributo o método van 2 guiones bajos
_NombreClase__atributo
_NombreClase__metodo()
```

In [474]:
class Person:
  def __init__(self, name, last_name, age, document):
    self.name = name
    self.last_name = last_name
    self.age = age
    # Defino un atributo privado
    self.__document = document

    # Al atributo full_name se le asigna el resultado 
    # de la función _create_full_name
    # para llamarlo se debe usar la palabra reservada self, así:
    # self._create_full_name()
    self.full_name = self.__create_full_name()

  # Defino un método privado
  def __create_full_name(self):
    return "{} {}".format(self.name, self.last_name)

In [475]:
diana = Person("Diana", "Sanchez", "20", "987654321")
print(diana.full_name)

Diana Sanchez


In [476]:
#print(diana.__create_full_name) # ERROR

In [477]:
# diana._NombreClase__Atributo
print(diana._Person__document)

987654321


In [478]:
# NO olviden los parentesis después del nombre del método
# diana._NombreClase__Método()
print(diana._Person__create_full_name())

Diana Sanchez


# Módulos Numpy, Pandas y Numba

## Numpy

Numpy es el módulo fundamental para la computación científica con Python. Es un paquete de funciones y herramientas matemáticas y numéricas de alto nivel que estáán diseñadas para trabajar con el objeto matriz numpy.

* Matrices multidimensionales
* Herramientas avanzadas para algebra líneal
* Funciones para trabajar con número aleatorios
* Su nucleo de procesamiento por debajo de Python está escrito en Fortran y C++

### Carga de módulo de Numpy

Es posible abreviar los namespaces mediante un alias. Para ello, durante la importación, se asigna la palabra clave **as** seguida del _alias_ con el cuál nos referiremos en el futuro a ese namespace importado:

In [479]:
# np = alias de numpy
import numpy as np

### Tipos de datos en Numpy

* Data type Description
* bool_ Boolean (True or False) stored as a byte
* int_ Default integer type (same as C long; normally either int64 or - int32)
* intc Identical to C int (normally int32 or int64)
* intp Integer used for indexing (same as C ssize_t; normally either - int32 or int64)
* int8 Byte (-128 to 127)
* int16 Integer (-32768 to 32767)
* int32 Integer (-2147483648 to 2147483647)
* int64 Integer (-9223372036854775808 to 9223372036854775807)
* uint8 Unsigned integer (0 to 255)
* uint16 Unsigned integer (0 to 65535)
* uint32 Unsigned integer (0 to 4294967295)
* uint64 Unsigned integer (0 to 18446744073709551615)
* float_ Shorthand for float64.
* float16 Half precision float: sign bit, 5 bits exponent, 10 bits - - mantissa
* float32 Single precision float: sign bit, 8 bits exponent, 23 bits - mantissa
* float64 Double precision float: sign bit, 11 bits exponent, 52 - - bits mantissa
* complex_ Shorthand for complex128.
* complex64 Complex number, represented by two 32-bit floats
* complex128 Complex number, represented by two 64-bit floats

### Creación de Matrices en Numpy

Una matriz unidimensional se puede comparar directamente con una lista de Python porque ambas pueden almacenar una lista de números. De manera similar los datos de una matriz se denominan elementos y se accede a ellos mediante corchetes `[]`.

Una matriz bidimensional tiene una estructura de cuadrícula con filas y columnas.

Una matriz tridimensional se puede considerar como una pila de matrices bidimensionales.

In [480]:
a = np.array([1, 2, 3, 4, 5, 6])   

print(a)
print(type(a))           
print(a.shape) # n filas, m columnas

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


**dtype:** El tipo de datos deseado para la matriz. Si no se proporciona, el tipo se determinará como el tipo mínimo requerido para contener los objetos en la secuencia.

In [481]:
a = np.array([0, 1, 2, 3, 4, 5, 6], dtype=np.float64)   

print(a)
print(type(a))      
print(a.shape)  # n filas, m columnas
print(a.ndim) # Dimensiones del array

[0. 1. 2. 3. 4. 5. 6.]
<class 'numpy.ndarray'>
(7,)
1


In [482]:
my_arr = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print(my_arr)
#[[1 2 3 4]
# [5 6 7 8]]

print(my_arr.ndim)  # Dimensiones de la matriz

print(my_arr.shape) # n filas, m columnas

print(my_arr.size)  # Número de elementos

print(type(my_arr)) # Tipo de elemento

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)
8
<class 'numpy.ndarray'>


#### Creación de arrays especiales
* Arrays con ceros
* Arrays con unos
* Arrays con constante
* Matriz identidad
* Arrays con números aleatorios

##### Arrays con ceros

In [483]:
a = np.zeros((5,3))   # 5 filas, 3 columnas

print(a)
print(a.shape)        # n filas, m columnas

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(5, 3)


In [484]:
a = np.zeros(shape=(5,4,3,2))

'''
[A] = [0, 0] -> (x, x, x, 2)
[B] = [ [A],
        [A], -> (x, x, 3, [A])
        [A]]
[C] = [ [B],
        [B], -> (x, 4, [B], [A])
        [B]
        [B]]
[D] = [ [C],
        [C]
        [C], -> (5, [C], [B], [A])
        [C]
        [C]
'''

print(a)
print(a.shape)  # número de elementos en cada dimensión

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]
(5, 4, 3, 2)


##### Arrays con unos

In [485]:
# Agregamos la dimensióón de la matriz para que esta sea llenada con 1s
a = np.ones((2,7))    

print(a)  

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


##### Arrays con constante

In [486]:
# np.ful((n filas, m columnas), cte)
a = np.full((4,4), 8)  

print(a)     

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


##### Matriz identidad

[numpy.eye](https://numpy.org/doc/stable/reference/generated/numpy.eye.html)

In [487]:
a = np.eye(5, k = 0)         

print(a) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [488]:
a = np.eye(5, k = 1)         

print(a) 

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


##### Arrays con números aleatorios

[numpy.random.random](http://pageperso.lif.univ-mrs.fr/~francois.denis/IAAM1/numpy-html-1.14.0/reference/generated/numpy.random.random.html)

In [489]:
# np.random.random((elementos por dimensión))
a = np.random.random((2,3,2))  
print(a) 

[[[0.21084268 0.58434361]
  [0.76587742 0.36081967]
  [0.79919535 0.1114408 ]]

 [[0.44156703 0.66844532]
  [0.42123687 0.05904446]
  [0.7370391  0.1225759 ]]]


In [490]:
a = np.random.random((2, 2))
print(a)

[[0.74018328 0.88769228]
 [0.71072869 0.46163317]]


In [491]:
# Obtener números aleatorios entre el rango:
# [-10, 0) -> el 0.000000 núnca es tomado

b = (10 * a) - 10
print(b)

[[-2.59816719 -1.12307724]
 [-2.89271309 -5.38366825]]


In [492]:
# Obtener números aleatorios entre el rango:
# (0, 10] -> el 0.000000 núnca es tomado

a = (-10 * a) + 10
print(a)

[[2.59816719 1.12307724]
 [2.89271309 5.38366825]]


#### Indexamiento de arrays de numpy

* Accediendo a elementos por indice
* Accediendo a elementos por slice

##### Accediendo a elementos por indice

In [493]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

'''
position:     0              1              2
              -3            -2              -1
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

position:  0  1  2  3
          -4 -3 -2 -1
          [5, 6, 7, 8]
'''   

print(a)

print(a[1])     # -> [5 6 7 8]

print(a[2][3])  # -> [9 10 11 12] -> 12

print(a[2,3])   # -> [9 10 11 12] -> 12

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
12
12


##### Accediendo a elementos por slice

In [530]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

'''
position:     0              1              2
             -3             -2             -1
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

position:  0  1  2  3
          -4 -3 -2 -1
          [5, 6, 7, 8]
'''  

print("a\n")
print(a)


print("\na[:2]\n")
# Primeras 2 filas
'''
[ [1 2 3 4]
  [5 6 7 8]]
'''
print(a[:2])


a

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

a[:2]

[[1 2 3 4]
 [5 6 7 8]]


In [531]:
'''
position:     0              1              2
             -3             -2             -1
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

position:  0  1  2  3
          -4 -3 -2 -1
          [5, 6, 7, 8]
'''  

print("\na[:2, -2:]\n")
# Ultimas 2 columnas de las 2 primeras filas
print(a[:2,-2:])


a[:2, -2:]

[[3 4]
 [7 8]]


In [536]:
'''
position:     0              1              2
             -3             -2             -1
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

position:  0  1  2  3
          -4 -3 -2 -1
          [5, 6, 7, 8]
'''  
print("\na[:2, -3:]\n")
# Ultimas 3 columnas de las 2 primeras filas
print(a[:2,-3:])


a[:2, -3:]

[[2 3 4]
 [6 7 8]]


In [538]:
'''
position:     0              1              2
             -3             -2             -1
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

position:  0  1  2  3
          -4 -3 -2 -1
          [5, 6, 7, 8]
'''  

print("\na[::-1, ::-1]\n")
# Se toman las filas una a una de atrás hacia adelante, es decir:
'''
Original:     [[1,2,3,4], [5,6,7,8], [9,10,11,12]] 
[::-1, X] ->  [[9, 10, 11, 12], [5, 6, 7, 8], [1, 2, 3, 4]]
'''
# Por cada fila, se tomarán los elementos de las columnas de atrás 
# hacia adelante, es decir:
'''
Original:     [9, 10, 11, 12]
[X, ::-1] ->  [12, 11, 10, 9]
'''
print(a[::-1, ::-1])
print('\n',a)


a[::-1, ::-1]

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Broadcasting con arrays de Numpy

El broadcasting es coger una operación aritmetica y replicarla a lo largo de un array de numpy

[np.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

In [540]:
# np.arange(inicio*, fin, saltos*, dtype=None) 
# los que tienen asterisco son opcionales
a = np.arange(10)
print(a, '\n')

# Genera una matriz con 2 filas X 5 columnas
'''
CUIDADO:
Las dimensiones del reshape deben contener exactamente la cantidad de elementos
de el array unidimencional
a = 10 elementos
a.reshape((2, 5)) -> 2*5 = 10
a.reshape((2, 6)) -> 2*6 = 12 ->ERROR
a.reshape((2, 4)) -> 2*4 = 8  ->ERROR
'''
a = a.reshape((2, 5))

b = a + 10

print(a, '\n')
print(b)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[10 11 12 13 14]
 [15 16 17 18 19]]


#### Operaciones por columna o por fila

In [499]:
a = np.arange(12)
a = a.reshape((3,4))

print(a, '\n')

print(np.sum(a))          # = 0 + 1 + 2 + 3 + ...+ 12

print(np.sum(a, axis=0)) 
# axis = 0 -> COLUMNA
'''
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
  
  12 15 18 21

12 = 0 + 4 + 8
15 = 1 + 5 + 9
21 = 3 + 7 + 11
'''

print(np.sum(a, axis=1))
# axis = 0 -> FILA

'''
[[ 0  1  2  3]  = 6
 [ 4  5  6  7]  = 22
 [ 8  9 10 11]] = 38

6  = 0 + 1 + 2 + 3
22 = 4 + 5 + 6 + 7
38 = 8 + 9 + 10 + 11
'''
print('\n ( ꈍᴗꈍ)')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

66
[12 15 18 21]
[ 6 22 38]

 ( ꈍᴗꈍ)


#### Operaciones matriciales elemento a elemento

In [500]:
a = np.arange(4)
a = a.reshape(2,2)

# np.arange(inicio*, fin, saltos*, dtype=None) 
# los que tienen asterisco son opcionales
b = np.arange(10,14)  # inicio = 10, fin = 14 -> [10, 14) = [10, 11, 12, 13]
b = b.reshape(2,2)    # Matriz 2X2 con los elementos del array unidimensional b

print(a, '\n')

print(b, '\n')

print(a / b)
'''
[ [0/10 1/11]
  [2/12 3/13]]
'''
print()

[[0 1]
 [2 3]] 

[[10 11]
 [12 13]] 

[[0.         0.09090909]
 [0.16666667 0.23076923]]



#### Indexado Booleano

In [542]:
# np.arange(inicio*, fin, saltos*, dtype=None) 
# los que tienen asterisco son opcionales
a = np.arange(16)           # Elementos en el rango [0, 16)
b = np.random.choice(a, 16) # Desorganiza los 16 elementos de forma aleatoria
b = b.reshape(4, 4)         # Crea una matriz 4X4

print('Matriz b\n')
print(b)

matriz_logica = b < 8       # Cada elemento de b es evaluado

print('\nMatriz matriz_logica\n')
print(matriz_logica)

c = b.copy()                # c es generado con una copia de b (matriz 4x4)
c[matriz_logica] = -1       # Si elemento == True -> nuevo valor = -1

print('\nMatriz c\n')
print(c)

Matriz b

[[ 4 15 12  3]
 [ 9  9  9  6]
 [13  2  4  2]
 [11  0 15  6]]

Matriz matriz_logica

[[ True False False  True]
 [False False False  True]
 [False  True  True  True]
 [False  True False  True]]

Matriz c

[[-1 15 12 -1]
 [ 9  9  9 -1]
 [13 -1 -1 -1]
 [11 -1 15 -1]]


## Pandas
pandas es una biblioteca de código abierto con licencia BSD que proporciona estructuras de datos y herramientas de análisis de datos de alto rendimiento; fáciles de usar para el lenguaje de programación Python.

### Carga de módulo de Pandas

In [502]:
# pd = alias de pandas
import pandas as pd

### Estructuras de datos en Pandas

* Series
* Dataframes

#### Series

Una serie es un array unidimensional (con tipos de datos de numpy), cada uno de sus elementos está etiquetado. Las etiquetas se llaman índices.

##### Creación de una serie

In [503]:
# Ejemplo

'''
 La primera columna inicia desde 0 por defecto y la segunda columna es poblada
 con los valores especificados en la lista
'''
serie1 = pd.Series([1,2,3,4,5,6])
print(serie1)
print(type(serie1))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>


##### Acceder a elementos e índices de una serie

In [504]:
# list() es un constructor que genera una lista

# Obtener valores
lista_valores = list(serie1.values) # lista de todos los valores de la serie1

print('lista_valores\n',lista_valores, '\n')

# Obtener índices
serie1.index
lista_indices = list(serie1.index)  # lista de todos los índices de la serie1

print('lista_indices\n', lista_indices)

lista_valores
 [1, 2, 3, 4, 5, 6] 

lista_indices
 [0, 1, 2, 3, 4, 5]


In [505]:
# Ejemplo de serie con index personalizados

serie1 = pd.Series([1,2,3,4,5,6], index=['a', 'b', 'c', 'd', 'e', 'f'])
print(serie1)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64


##### Transformar un diccionario en una serie


In [506]:
# Ejemplo de una Serie construida desde un diccionario

dic = {0: 'a', 1: 'b', 2: 'c'}
pd.Series(dic)

0    a
1    b
2    c
dtype: object

##### Opeaciones con series

* Broadcasting
* indexado booleano

In [507]:
# Ejemplo
import string
print('letras ascii\n', string.ascii_letters, '\n')

# Toma las primeras 10 letras ascii y genera una lista llamada 'index'
index = list(string.ascii_letters)[:10]

# Genera una Serie donde:
'''
valores = números entre el rango [0, 10)
indices = lista 'index' que tiene las 10 primeras letras ascii
'''
serie1 = pd.Series(np.arange(10), index=index)
print('Serie1\n')
print(serie1, '\n')

letras ascii
 abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ 

Serie1

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
i    8
j    9
dtype: int64 



In [508]:
# Broadcasting
serie2 = serie1 * 3       # multiplico cada uno de los valores de serie1 por 3
print('Serie2\n')
print(serie2, '\n')

# Aplico raiz cuadrada a cada uno de los valores de serie1
serie3 = np.sqrt(serie1)
print('Serie3\n')
print(serie3, '\n')

Serie2

a     0
b     3
c     6
d     9
e    12
f    15
g    18
h    21
i    24
j    27
dtype: int64 

Serie3

a    0.000000
b    1.000000
c    1.414214
d    1.732051
e    2.000000
f    2.236068
g    2.449490
h    2.645751
i    2.828427
j    3.000000
dtype: float64 



In [509]:
# Indexado booleano
serie4 = serie1[serie1 >= 5]
print('Serie1\n')
print(serie4, '\n')

# Ejemplo con error
# serie5 = serie1[serie1 >= 5 and serie1 <= 7]
'''
El 'and' comun espera dos valores booleanos para operar:
T and F 

Sin embargo se le esta mostrando una lista de valores booleanos: 
[T, F, T, T] and [T, T, F, T] -> error

np.logical_and([T, F, T, T], [T, T, F, T]) = [T, F, F, T]
'''
serie5 = serie1[np.logical_and(serie1 >= 5, serie1 <= 7)]
print('Serie5\n')
print(serie5)

Serie1

f    5
g    6
h    7
i    8
j    9
dtype: int64 

Serie5

f    5
g    6
h    7
dtype: int64


#### Data Frames

Un Dataframe es una estructura de datos que sirve para crear tablas bidimensionales, en donde a cada dimensión tiene etiquetas para acceder a los datos.

##### Creación de dataframes

In [510]:
# Definición de un diccionario
dc = {'Nombre': ['Francisco', 'Mario', 'Ana', 'Pedro', 'Marta'],
      'Edad': [37, 20, 45, 26, 42],
      'Género': ['M', 'M', 'F', 'M', 'F']}
# df1 es un dataframe creado a partir del diccionario dc
df1 = pd.DataFrame(dc)
df1

Nombre  Edad Género
0  Francisco    37      M
1      Mario    20      M
2        Ana    45      F
3      Pedro    26      M
4      Marta    42      F

##### Acceso a índices por columnas o por filas

In [511]:
# Ejemplo
# Por columnas
print(df1.columns)

# Por filas
print(df1.index)  #[0, 5)

Index(['Nombre', 'Edad', 'Género'], dtype='object')
RangeIndex(start=0, stop=5, step=1)


##### Acceso a los datos por columnas o por filas

In [512]:
# Ejemplo de acceso por columnas

print(df1['Edad'], '\n') 

print('Type: ',type(df1['Edad']), '\n')# El retorno es una Serie

print(df1[['Nombre', 'Edad']], '\n')

# Acceder como atributo
print(df1.Edad)

0    37
1    20
2    45
3    26
4    42
Name: Edad, dtype: int64 

Type:  <class 'pandas.core.series.Series'> 

      Nombre  Edad
0  Francisco    37
1      Mario    20
2        Ana    45
3      Pedro    26
4      Marta    42 

0    37
1    20
2    45
3    26
4    42
Name: Edad, dtype: int64


[diferencia loc e iloc](https://www.analyticslane.com/2019/06/21/seleccionar-filas-y-columnas-en-pandas-con-iloc-y-loc/)

In [513]:
# Ejemplo de acceso por filas

# Llaves  Valores de la fila
print(df1.loc[0], '\n')

print('Type:',type(df1.iloc[0]), '\n') # El retorno es una Serie

df2 = df1.copy()

# Se redefine el valor de los indices para df2 -> [10, 15)
df2.index = np.arange(10,15)
print(df2, '\n')

# df2.loc[0]  #error porque el indice 0 no existe
df2.iloc[0]

Nombre    Francisco
Edad             37
Género            M
Name: 0, dtype: object 

Type: <class 'pandas.core.series.Series'> 

       Nombre  Edad Género
10  Francisco    37      M
11      Mario    20      M
12        Ana    45      F
13      Pedro    26      M
14      Marta    42      F 



Nombre    Francisco
Edad             37
Género            M
Name: 10, dtype: object

In [514]:
# Eliminar personas cuya edad sea menor o igual a 40
df2 = df1[df1['Edad'] > 40]
print(df2)

  Nombre  Edad Género
2    Ana    45      F
4  Marta    42      F


In [515]:
df2.iloc[0]

# Hay un error porque el indice 0 fue eliminado, solo estan 2 y 4
# df2.loc[0]

Nombre    Ana
Edad       45
Género      F
Name: 2, dtype: object

##### Obtener todos los elementos de un DataFrame como un array de numpy

In [516]:
# Ejemplob
df1.values

array([['Francisco', 37, 'M'],
       ['Mario', 20, 'M'],
       ['Ana', 45, 'F'],
       ['Pedro', 26, 'M'],
       ['Marta', 42, 'F']], dtype=object)

##### Formas de iterar un dataframe de pandas

* Con un for convencional
* Con un iterrows
* Con una función lambda

In [517]:
! wget https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

--2020-09-20 20:33:48--  https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4551 (4.4K) [application/x-httpd-php]
Saving to: ‘iris.data.4’

iris.data.4         100%[===================>]   4.44K  --.-KB/s    in 0s      

2020-09-20 20:33:48 (99.8 MB/s) - ‘iris.data.4’ saved [4551/4551]



In [518]:
! head -n 5 iris.data

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa


In [519]:
iris = pd.read_csv('iris.data', header=None)
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris

sepal_length  sepal_width  petal_length  petal_width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

###### Con un for convencional

In [520]:
from datetime import datetime as dt

start = dt.now()

sepal_box = np.zeros(len(iris))
# np.arange(len(iris)) -> [0, len(iris))
for index in np.arange(len(iris)):
    # row_act = contiene los valores de la fila recorrida en esa iteración
    row_act = iris.iloc[index]
    sepal_box[index] = row_act['sepal_length'] * row_act['sepal_width']
print(dt.now() - start)

0:00:00.029514


###### Con un iterrows

In [521]:
start = dt.now()

sepal_box = np.zeros(len(iris))

for index, row in iris.iterrows():
    sepal_box[index] = row['sepal_length'] * row['sepal_width']
    
print(dt.now() - start)

0:00:00.023896


###### Con una función lambda

In [522]:
def get_box(row):
    return row['sepal_length'] * row['sepal_width']

get_box(iris.iloc[0])

17.849999999999998

In [523]:
start = dt.now()

# axis=1  ->  filas
sepal_box = iris.apply(lambda row: get_box(row), axis=1)

print(dt.now() - start)

0:00:00.010792


## Numba

Numba es un módulo de python que permite convertir código de python directamenet a código de máquina para obtener tiempos de ejecución **muchísimo** mas eficientes.


In [524]:
import numpy as np

n = 1e7
array = np.random.rand(int(n)) * 360
print(array)

[ 31.73389241  64.97720092 348.00306802 ... 129.70698296  80.60581405
 285.18499785]


In [525]:
from datetime import datetime as dt


def sin_array(array):
    ret = np.empty(len(array))
    for index, x in enumerate(array):
        ret[index] = np.sin(x * 2 * np.pi / 360)
    return ret


start = dt.now()

sin_array(array)

print(dt.now() - start)

0:00:26.747090


In [526]:
import numba

@numba.jit
def sin_array2(array):
    ret = np.empty(len(array))
    for index, x in enumerate(array):
        ret[index] = np.sin(x * 2 * np.pi / 360)
    return ret

start = dt.now()

sin_array2(array)

print(dt.now() - start)

0:00:00.498549
